FROM ghcr.io/2635064692/novelwriter:1b05753

COPY --from=ghcr.io/astral-sh/uv:0.10.4 /uv /usr/local/bin/uv
COPY pyproject.toml uv.lock ./
RUN --mount=type=cache,target=/root/.cache/uv \
    UV_INDEX_URL=https://mirrors.aliyun.com/pypi/simple/ \
    uv sync --no-dev

COPY web/dist/ /app/static/
COPY app/ /app/app/
COPY alembic/ /app/alembic/
COPY data/ /app/data/
COPY resources/key/isrgrootx1.pem /app/resources/key/isrgrootx1.pem
