import { registerUiMessages, type UiMessageValue, type UiMessageParams } from '@/lib/uiMessages'

export const copilotZhMessages = {
  'copilot.scope.wholeBook': '全书研究',
  'copilot.scope.draftContext': '草稿上下文',
  'copilot.scope.relationshipContext': '关系上下文',
  'copilot.scope.entityContext': '实体上下文',

  'copilot.session.title.wholeBook': '全书探索',
  'copilot.session.title.draftCleanup': '草稿整理',
  'copilot.session.title.relationshipContext': '关系上下文',
  'copilot.session.title.entityContext': '实体补完',
  'copilot.session.title.currentContext': '当前上下文',
  'copilot.session.title.entityWithId': ({ id }) => `实体 ${String(id ?? '')}`,
  'copilot.session.title.relationshipWithEntityId': ({ id }) => `实体 ${String(id ?? '')} ↔ 相关实体`,
  'copilot.session.title.relationshipWithName': ({ name }) => `${String(name ?? '').trim()} ↔ 相关实体`,

  'copilot.drawer.badge': 'Novel Copilot',
  'copilot.drawer.sessionsCount': ({ count }) => `${String(count ?? 0)} 个会话`,
  'copilot.drawer.currentWorkspace': ({ title }) => `当前工作区：${String(title ?? '')}`,
  'copilot.drawer.workspace': '工作区',
  'copilot.drawer.currentRequest': '当前请求',
  'copilot.drawer.previousRequest': '之前的请求',
  'copilot.drawer.interrupted': '已中断',
  'copilot.drawer.interruptedFallback': '这轮研究已中断，请稍后重试。',
  'copilot.drawer.retryInterrupted': '恢复上次研究',
  'copilot.drawer.retryingInterrupted': '恢复中…',
  'copilot.drawer.retryHint': '恢复将继续上次检索进度；如需换问题，请直接在下方输入新请求。',
  'copilot.drawer.cancel': '取消研究',
  'copilot.drawer.errorFallback': '本轮运行出现异常，请稍后重试。',
  'copilot.drawer.analysisResult': '分析结果',
  'copilot.drawer.suggestions': '建议列表',
  'copilot.drawer.pendingSuggestions': ({ count }) => `${String(count ?? 0)} 条待确认`,
  'copilot.drawer.applied': '已采纳',
  'copilot.drawer.appliedSuggestions': ({ count }) => `${String(count ?? 0)} 条已保留`,
  'copilot.drawer.noSuggestions': '未找到相关的建议。',
  'copilot.drawer.allHandled': '本轮待处理建议已全部处理；已采纳建议保留在当前会话中。',
  'copilot.drawer.fallbackPrompt': '请基于当前上下文给出高价值建议。',
  'copilot.drawer.expand': '放大 Copilot',
  'copilot.drawer.exitExpanded': '退出放大',
  'copilot.drawer.close': '关闭 Copilot',

  'copilot.composer.defaultLabel': '补充要求',
  'copilot.composer.defaultPlaceholder': '输入补充要求，例如“优先补足苏瑶与宗门的关联线索”',
  'copilot.composer.sendHint': 'Enter 发送 / Shift+Enter 换行',
  'copilot.composer.send': '发送',

  'copilot.sessionStrip.title': '并行工作区',
  'copilot.sessionStrip.hint': '切换查看不会中断后台运行',
  'copilot.sessionStrip.current': '当前',
  'copilot.sessionStrip.close': '关闭会话',
  'copilot.sessionStrip.newSession': '新建同类会话',

  'copilot.runStatus.queued': '排队中',
  'copilot.runStatus.running': '运行中',
  'copilot.runStatus.interrupted': '已中断',
  'copilot.runStatus.error': '异常',
  'copilot.runStatus.completed': '已完成',
  'copilot.runStatus.idle': '待命',

  'copilot.aiStatus.idle': 'AI 就绪',
  'copilot.aiStatus.connected': 'AI 已连接',
  'copilot.aiStatus.running': 'AI 思考中',
  'copilot.aiStatus.error': 'AI 异常',

  'copilot.suggestion.kind.entity': '实体',
  'copilot.suggestion.kind.relationship': '关系',
  'copilot.suggestion.kind.system': '体系',
  'copilot.suggestion.source.chapterExcerpt': '章节片段',
  'copilot.suggestion.source.worldEntity': '设定条目',
  'copilot.suggestion.source.worldRelationship': '关系设定',
  'copilot.suggestion.source.worldSystem': '体系设定',
  'copilot.suggestion.source.evidencePack': '相关线索',
  'copilot.suggestion.source.draftReview': '草稿项',
  'copilot.suggestion.evidenceCount': ({ count }) => `${String(count ?? 0)} 条依据`,
  'copilot.suggestion.actionable': '可直接采纳',
  'copilot.suggestion.referenceOnly': '仅供参考',
  'copilot.suggestion.applied': '已采纳',
  'copilot.suggestion.changePreview': '变更预览',
  'copilot.suggestion.target': '目标:',
  'copilot.suggestion.previousValue': '原值 :',
  'copilot.suggestion.newValue': '新值 :',
  'copilot.suggestion.emptyValue': '(空)',
  'copilot.suggestion.keyEvidence': '关键依据',
  'copilot.suggestion.appliedNote': '已采纳此建议。',
  'copilot.suggestion.collapsePreview': '收起预览',
  'copilot.suggestion.expandPreview': '展开预览',
  'copilot.suggestion.locate': '查看目标',
  'copilot.suggestion.dismiss': '忽略',
  'copilot.suggestion.apply': '采纳',
  'copilot.suggestion.notActionable': '当前不能直接采纳',

  'copilot.research.chapterLabel': ({ chapter }) => `第${String(chapter ?? '')}章`,
  'copilot.research.detail.moreContext': '更多上下文',
  'copilot.research.detail.relatedEvidence': '相关依据',
  'copilot.research.detail.fullEvidence': '完整依据',
  'copilot.research.state.expandedContext': '已展开更多上下文',
  'copilot.research.state.clueSummary': '线索摘要',
  'copilot.research.reason.fromRelatedClues': '已从相关线索中整理',
  'copilot.research.reason.fromExpandedContext': '已展开更多上下文',
  'copilot.research.reason.fromToolResults': '已从检索结果整理',
  'copilot.research.tool.find': '搜索线索',
  'copilot.research.tool.open': '展开上下文',
  'copilot.research.tool.read': '读取设定',
  'copilot.research.tool.mode': '研究过程',
  'copilot.research.tool.step': '研究步骤',
  'copilot.research.summary.toolSteps': ({ count }) => `${String(count ?? 0)} 步检索`,
  'copilot.research.summary.evidenceCount': ({ count }) => `${String(count ?? 0)} 条依据`,
  'copilot.research.summary.processing': '处理中',
  'copilot.research.summary.none': '暂无依据',
  'copilot.research.panelLabel': '研究过程',
  'copilot.research.expand': '展开研究过程',
  'copilot.research.collapse': '收起研究过程',
  'copilot.research.viewable': '可查看',
  'copilot.research.searchProcess': '检索过程',
  'copilot.research.relatedEvidenceSection': '相关依据',
  'copilot.research.processDescription': '过程说明',
  'copilot.research.processNote': '这里展示的是本轮检索步骤摘要，用来解释这次回答如何整理出来；它不是原文依据。',

  'copilot.card.aiTools': 'AI 工具',
  'copilot.card.workbenchEyebrow': '研究工作台',
  'copilot.card.workbenchDescription': '从全书视角检索设定缺口、潜在线索与值得进一步研究的世界锚点。',
  'copilot.card.wholeBook': '全书探索',
  'copilot.card.triggerTitle': 'Novel Copilot',
  'copilot.card.triggerCompactDescription': '全书探索与上下文研究',
  'copilot.card.triggerDescription': '跨章节研究世界状态、设定缺口与潜在线索',
  'copilot.card.openWholeBook': '打开全书研究',
  'copilot.card.atlasSummary': ({ entities, relationships, systems }: UiMessageParams) => `当前世界：${String(entities ?? 0)}个实体 · ${String(relationships ?? 0)}个关系 · ${String(systems ?? 0)}个体系`,
  'copilot.card.atlasSummaryEmpty': '当前世界尚未建立条目',
  'copilot.card.generateDrafts': '从设定生成草稿',
  'copilot.card.outlineManager': '大纲管理',
  'copilot.card.outlineManagerDescription': '生成卷纲、章纲并审核结构化大纲',
  'copilot.card.batchOps': '批量生成与初始化',
  'copilot.card.generateFromSettings': '从设定生成',
  'copilot.card.generateFromSettingsLong': '从设定文本生成 (大段输入)',

  'copilot.workbench.wholeBook.eyebrow': '研究工作台',
  'copilot.workbench.wholeBook.title': '从全书视角检索世界状态、设定缺口与潜在线索。',
  'copilot.workbench.wholeBook.composerLabel': '研究问题',
  'copilot.workbench.wholeBook.composerPlaceholder': '输入研究问题，例如“盘点全书里反复出现但尚未入模的势力、地点和规则”',
  'copilot.workbench.wholeBook.scanGaps.label': '盘点设定缺口',
  'copilot.workbench.wholeBook.scanGaps.description': '找出反复出现却仍未入模的对象与规则',
  'copilot.workbench.wholeBook.scanGaps.prompt': '请从全书角度盘点反复出现但尚未进入世界模型的势力、地点、规则或概念。',
  'copilot.workbench.wholeBook.traceSignals.label': '梳理高频线索',
  'copilot.workbench.wholeBook.traceSignals.description': '聚焦势力、地点与规则的关键锚点',
  'copilot.workbench.wholeBook.traceSignals.prompt': '请梳理全书里反复出现的势力、地点与规则线索，并指出最值得进一步研究的世界锚点。',
  'copilot.workbench.wholeBook.findConflicts.label': '定位冲突风险',
  'copilot.workbench.wholeBook.findConflicts.description': '提前发现命名漂移与设定空洞',
  'copilot.workbench.wholeBook.findConflicts.prompt': '请检查章节高频提及与当前世界模型之间的命名冲突、设定漂移和明显空洞。',

  'copilot.workbench.entity.eyebrow': '实体补完',
  'copilot.workbench.entity.title': ({ subject }) => `围绕 ${String(subject ?? '')} 补足类型、属性、约束与关联线索，不要默认它只是人物。`,
  'copilot.workbench.entity.composerLabel': '补充要求',
  'copilot.workbench.entity.composerPlaceholder': ({ subject }) => `输入补充要求，例如“优先补足${String(subject ?? '')}与宗门的关联线索”`,
  'copilot.workbench.entity.complete.label': '补完当前实体',
  'copilot.workbench.entity.complete.description': '补足类别、属性、别名与关键约束',
  'copilot.workbench.entity.complete.prompt': ({ subject }) => `请补完 ${String(subject ?? '')} 的关键设定。实体不只可能是人物，也可能是势力、地点、组织、物件或概念；请先判断类型，再补足别名、属性、约束和关联线索。`,
  'copilot.workbench.entity.findRelations.label': '挖掘关系线索',
  'copilot.workbench.entity.findRelations.description': '检索互动证据与潜在连接',
  'copilot.workbench.entity.findRelations.prompt': ({ subject }) => `请围绕 ${String(subject ?? '')} 梳理最值得确认的关系线索与潜在连接。`,
  'copilot.workbench.entity.collectEvidence.label': '汇总章节证据',
  'copilot.workbench.entity.collectEvidence.description': '集中查看支撑补完的关键片段',
  'copilot.workbench.entity.collectEvidence.prompt': ({ subject }) => `请汇总最能支撑 ${String(subject ?? '')} 补完的章节证据，并按重要性排序。`,

  'copilot.workbench.relationships.eyebrow': '关系研究',
  'copilot.workbench.relationships.title': ({ subject }) => `围绕 ${String(subject ?? '')} 梳理缺失关系、互动证据与标签表述。`,
  'copilot.workbench.relationships.composerLabel': '关系研究目标',
  'copilot.workbench.relationships.composerPlaceholder': ({ subject }) => `输入关系研究目标，例如“找出${String(subject ?? '')}与各势力之间缺失但有证据的连接”`,
  'copilot.workbench.relationships.find.label': '补全缺失关系',
  'copilot.workbench.relationships.find.description': '围绕中心实体找出最值得确认的连接',
  'copilot.workbench.relationships.find.prompt': ({ subject }) => `请围绕 ${String(subject ?? '')} 梳理最值得确认的关系线索、缺失连接与关系方向。`,
  'copilot.workbench.relationships.labeling.label': '统一关系标签',
  'copilot.workbench.relationships.labeling.description': '清理含混、重复或过弱的表述',
  'copilot.workbench.relationships.labeling.prompt': ({ subject }) => `请统一 ${String(subject ?? '')} 相关关系的标签表述，并指出含混、重复或语义过弱的关系。`,
  'copilot.workbench.relationships.collect.label': '汇总互动证据',
  'copilot.workbench.relationships.collect.description': '回看关键人物、势力与章节片段',
  'copilot.workbench.relationships.collect.prompt': ({ subject }) => `请汇总 ${String(subject ?? '')} 与关键人物、势力互动的章节证据，并标出最值得建模的连接。`,

  'copilot.workbench.draft.eyebrow': '草稿清理',
  'copilot.workbench.draft.title': '整理现有草稿，统一命名、补足缺失字段，并标记可直接确认的候选。',
  'copilot.workbench.draft.composerLabel': '清理目标',
  'copilot.workbench.draft.composerPlaceholder': '输入清理目标，例如“统一草稿命名并标出最值得先确认的条目”',
  'copilot.workbench.draft.review.label': '筛出优先草稿',
  'copilot.workbench.draft.review.description': '找出最值得优先确认或补完的条目',
  'copilot.workbench.draft.review.prompt': '请整理当前草稿并指出最值得优先处理的缺口。',
  'copilot.workbench.draft.normalize.label': '统一草稿命名',
  'copilot.workbench.draft.normalize.description': '收束重复概念与别名漂移',
  'copilot.workbench.draft.normalize.prompt': '请统一当前草稿中的命名、别名和重复概念，优先指出可直接清理的候选。',
  'copilot.workbench.draft.fill.label': '补足缺失字段',
  'copilot.workbench.draft.fill.description': '找出描述过短或字段缺失的草稿',
  'copilot.workbench.draft.fill.prompt': '请找出当前草稿中字段缺失、描述过短或明显可补完的条目，并按价值排序。',

  'copilot.errors.pollRunNotFound': '这轮研究已失效，请重新发起。',
  'copilot.errors.connectionInterrupted': '连接中断，请稍后重试。',
  'copilot.errors.applyTargetStale': '这条建议对应的内容刚刚发生了变化，请刷新后再试一次。',
  'copilot.errors.applyNotActionable': '这条建议目前还不能直接采纳。',
  'copilot.errors.applySuggestionNotFound': '这条建议已经失效了，请重新生成一次。',
  'copilot.errors.applyFailed': '这次确认没有成功，请稍后再试。',
  'copilot.errors.sessionRunActive': '当前会话里已有一轮研究正在进行，请等它完成后再继续。',
  'copilot.errors.tooManyActiveRuns': '你当前同时进行的研究轮次已达上限，请先等待其他会话完成。',
  'copilot.errors.tooManyGlobalRuns': '当前服务器较忙，正在处理过多的 Copilot 请求，请稍后再试。',
  'copilot.errors.resumeRunNotFound': '这轮中断的研究已经找不到了，请直接重新发起一个新问题。',
  'copilot.errors.resumeRunNotInterrupted': '这轮研究当前不处于可恢复状态，请刷新后再试。',
  'copilot.errors.resumePromptMismatch': '恢复旧研究时不能更换问题；如需新问题，请直接在下方输入。',
  'copilot.errors.resumeRunNotResumable': '这轮中断研究缺少可恢复进度，请直接重新发起。',
  'copilot.errors.quotaExhausted': '可用额度已用完，请先提交反馈解锁更多额度。',
  'copilot.errors.requestBusy': '当前请求较多，请稍后再试。',
  'copilot.errors.serviceUnavailable': '当前服务暂时不可用，请稍后再试。',
  'copilot.errors.sessionConflict': '当前会话状态暂时不允许发起新的研究，请稍后再试。',
  'copilot.errors.runCreateFailed': '暂时无法发起这一轮研究，请稍后重试。',
  'copilot.errors.connecting': '正在连接...',

  // Model selector
  'copilot.model.default': '默认模型',
  'copilot.model.noProviders': '请先在设置中配置模型提供商',
  'copilot.history.title': '历史会话',
  'copilot.history.empty': '暂无历史会话',
  'copilot.history.emptyHint': '开始一次 Copilot 研究，它会自动出现在这里。',
  'copilot.history.loadMore': '加载更多',
  'copilot.history.loading': '加载中...',
  'copilot.history.runs': ({ count }) => `${String(count ?? 0)} 轮`,
  'copilot.history.restore': '恢复会话',
  'copilot.history.filter.all': '全部',
  'copilot.history.filter.research': '研究',
  'copilot.history.filter.currentEntity': '实体',
  'copilot.history.filter.draftCleanup': '草稿',
  'copilot.history.mode.research': '研究',
  'copilot.history.mode.current_entity': '实体',
  'copilot.history.mode.draft_cleanup': '草稿',
  'copilot.history.scope.whole_book': '全书',
  'copilot.history.scope.current_entity': '实体',
  'copilot.history.scope.current_tab': '标签页',
} as const satisfies Record<string, UiMessageValue>

export const copilotEnMessages = {
  'copilot.scope.wholeBook': 'Whole-book research',
  'copilot.scope.draftContext': 'Draft context',
  'copilot.scope.relationshipContext': 'Relationship context',
  'copilot.scope.entityContext': 'Entity context',

  'copilot.session.title.wholeBook': 'Whole-book exploration',
  'copilot.session.title.draftCleanup': 'Draft cleanup',
  'copilot.session.title.relationshipContext': 'Relationship context',
  'copilot.session.title.entityContext': 'Entity enrichment',
  'copilot.session.title.currentContext': 'Current context',
  'copilot.session.title.entityWithId': ({ id }) => `Entity ${String(id ?? '')}`,
  'copilot.session.title.relationshipWithEntityId': ({ id }) => `Entity ${String(id ?? '')} ↔ Related entities`,
  'copilot.session.title.relationshipWithName': ({ name }) => `${String(name ?? '').trim()} ↔ Related entities`,

  'copilot.drawer.badge': 'Novel Copilot',
  'copilot.drawer.sessionsCount': ({ count }) => `${String(count ?? 0)} sessions`,
  'copilot.drawer.currentWorkspace': ({ title }) => `Current workspace: ${String(title ?? '')}`,
  'copilot.drawer.workspace': 'Workspace',
  'copilot.drawer.currentRequest': 'Current request',
  'copilot.drawer.previousRequest': 'Previous request',
  'copilot.drawer.interrupted': 'Interrupted',
  'copilot.drawer.interruptedFallback': 'This research run was interrupted. Please try again shortly.',
  'copilot.drawer.retryInterrupted': 'Resume previous research',
  'copilot.drawer.retryingInterrupted': 'Resuming...',
  'copilot.drawer.retryHint': 'Resuming will continue from the previous search progress. To ask a different question, enter a new request below.',
  'copilot.drawer.cancel': 'Cancel',
  'copilot.drawer.errorFallback': 'This run encountered an error. Please try again shortly.',
  'copilot.drawer.analysisResult': 'Analysis',
  'copilot.drawer.suggestions': 'Suggestions',
  'copilot.drawer.pendingSuggestions': ({ count }) => `${String(count ?? 0)} pending`,
  'copilot.drawer.applied': 'Applied',
  'copilot.drawer.appliedSuggestions': ({ count }) => `${String(count ?? 0)} retained`,
  'copilot.drawer.noSuggestions': 'No relevant suggestions were found.',
  'copilot.drawer.allHandled': 'All pending suggestions in this run have been handled. Applied suggestions remain in the current session.',
  'copilot.drawer.fallbackPrompt': 'Please provide high-value suggestions based on the current context.',
  'copilot.drawer.expand': 'Expand Copilot',
  'copilot.drawer.exitExpanded': 'Exit expanded view',
  'copilot.drawer.close': 'Close Copilot',

  'copilot.composer.defaultLabel': 'Additional requirements',
  'copilot.composer.defaultPlaceholder': 'Add more detail, such as "Prioritize Su Yao\'s links with the sect"',
  'copilot.composer.sendHint': 'Press Enter to send / Shift+Enter for a new line',
  'copilot.composer.send': 'Send',

  'copilot.sessionStrip.title': 'Parallel workspaces',
  'copilot.sessionStrip.hint': 'Switching views will not interrupt background runs',
  'copilot.sessionStrip.current': 'Current',
  'copilot.sessionStrip.close': 'Close session',
  'copilot.sessionStrip.newSession': 'New session',

  'copilot.runStatus.queued': 'Queued',
  'copilot.runStatus.running': 'Running',
  'copilot.runStatus.interrupted': 'Interrupted',
  'copilot.runStatus.error': 'Error',
  'copilot.runStatus.completed': 'Completed',
  'copilot.runStatus.idle': 'Idle',

  'copilot.aiStatus.idle': 'AI ready',
  'copilot.aiStatus.connected': 'AI connected',
  'copilot.aiStatus.running': 'AI thinking',
  'copilot.aiStatus.error': 'AI error',

  'copilot.suggestion.kind.entity': 'Entity',
  'copilot.suggestion.kind.relationship': 'Relationship',
  'copilot.suggestion.kind.system': 'System',
  'copilot.suggestion.source.chapterExcerpt': 'Chapter excerpt',
  'copilot.suggestion.source.worldEntity': 'World entry',
  'copilot.suggestion.source.worldRelationship': 'Relationship entry',
  'copilot.suggestion.source.worldSystem': 'System entry',
  'copilot.suggestion.source.evidencePack': 'Related clues',
  'copilot.suggestion.source.draftReview': 'Draft item',
  'copilot.suggestion.evidenceCount': ({ count }) => `${String(count ?? 0)} evidence`,
  'copilot.suggestion.actionable': 'Directly applicable',
  'copilot.suggestion.referenceOnly': 'Reference only',
  'copilot.suggestion.applied': 'Applied',
  'copilot.suggestion.changePreview': 'Change preview',
  'copilot.suggestion.target': 'Target:',
  'copilot.suggestion.previousValue': 'Before:',
  'copilot.suggestion.newValue': 'After:',
  'copilot.suggestion.emptyValue': '(empty)',
  'copilot.suggestion.keyEvidence': 'Key evidence',
  'copilot.suggestion.appliedNote': 'This suggestion has been applied.',
  'copilot.suggestion.collapsePreview': 'Collapse preview',
  'copilot.suggestion.expandPreview': 'Expand preview',
  'copilot.suggestion.locate': 'View target',
  'copilot.suggestion.dismiss': 'Dismiss',
  'copilot.suggestion.apply': 'Apply',
  'copilot.suggestion.notActionable': 'Cannot be applied directly right now',

  'copilot.research.chapterLabel': ({ chapter }) => `Chapter ${String(chapter ?? '')}`,
  'copilot.research.detail.moreContext': 'More context',
  'copilot.research.detail.relatedEvidence': 'Related evidence',
  'copilot.research.detail.fullEvidence': 'Full evidence',
  'copilot.research.state.expandedContext': 'Expanded more context',
  'copilot.research.state.clueSummary': 'Clue summary',
  'copilot.research.reason.fromRelatedClues': 'Compiled from related clues',
  'copilot.research.reason.fromExpandedContext': 'Compiled from expanded context',
  'copilot.research.reason.fromToolResults': 'Compiled from search results',
  'copilot.research.tool.find': 'Search clues',
  'copilot.research.tool.open': 'Expand context',
  'copilot.research.tool.read': 'Read world data',
  'copilot.research.tool.mode': 'Research process',
  'copilot.research.tool.step': 'Research step',
  'copilot.research.summary.toolSteps': ({ count }) => `${String(count ?? 0)} search steps`,
  'copilot.research.summary.evidenceCount': ({ count }) => `${String(count ?? 0)} evidence`,
  'copilot.research.summary.processing': 'Processing',
  'copilot.research.summary.none': 'No evidence yet',
  'copilot.research.panelLabel': 'Research process',
  'copilot.research.expand': 'Expand research process',
  'copilot.research.collapse': 'Collapse research process',
  'copilot.research.viewable': 'Viewable',
  'copilot.research.searchProcess': 'Search process',
  'copilot.research.relatedEvidenceSection': 'Related evidence',
  'copilot.research.processDescription': 'Process notes',
  'copilot.research.processNote': 'This area shows a summary of the search steps for this run. It explains how the answer was assembled, but it is not the original source evidence.',

  'copilot.card.aiTools': 'AI tools',
  'copilot.card.workbenchEyebrow': 'Research workbench',
  'copilot.card.workbenchDescription': 'Search for world-model gaps, latent clues, and high-value anchors across the whole book.',
  'copilot.card.wholeBook': 'Whole-book exploration',
  'copilot.card.triggerTitle': 'Novel Copilot',
  'copilot.card.triggerCompactDescription': 'Whole-book exploration and contextual research',
  'copilot.card.triggerDescription': 'Research world state, modeling gaps, and latent clues across chapters',
  'copilot.card.openWholeBook': 'Open whole-book research',
  'copilot.card.atlasSummary': ({ entities, relationships, systems }: UiMessageParams) => `Current world: ${String(entities ?? 0)} entities · ${String(relationships ?? 0)} relationships · ${String(systems ?? 0)} systems`,
  'copilot.card.atlasSummaryEmpty': 'No world entries have been created yet',
  'copilot.card.generateDrafts': 'Generate drafts from world data',
  'copilot.card.outlineManager': 'Outline management',
  'copilot.card.outlineManagerDescription': 'Generate volume/chapter outlines and review the structured outline',
  'copilot.card.batchOps': 'Batch generation and initialization',
  'copilot.card.generateFromSettings': 'Generate from settings',
  'copilot.card.generateFromSettingsLong': 'Generate from source text (long input)',

  'copilot.workbench.wholeBook.eyebrow': 'Research workbench',
  'copilot.workbench.wholeBook.title': 'Search world state, modeling gaps, and latent clues from a whole-book perspective.',
  'copilot.workbench.wholeBook.composerLabel': 'Research question',
  'copilot.workbench.wholeBook.composerPlaceholder': 'Ask a question such as "List recurring factions, locations, and rules that still are not modeled"',
  'copilot.workbench.wholeBook.scanGaps.label': 'Scan for modeling gaps',
  'copilot.workbench.wholeBook.scanGaps.description': 'Find recurring objects and rules that still are not modeled',
  'copilot.workbench.wholeBook.scanGaps.prompt': 'From a whole-book perspective, list recurring factions, locations, rules, or concepts that still have not entered the world model.',
  'copilot.workbench.wholeBook.traceSignals.label': 'Trace high-frequency clues',
  'copilot.workbench.wholeBook.traceSignals.description': 'Focus on key anchors for factions, locations, and rules',
  'copilot.workbench.wholeBook.traceSignals.prompt': 'Trace recurring faction, location, and rule clues across the whole book, and point out the world anchors most worth further research.',
  'copilot.workbench.wholeBook.findConflicts.label': 'Locate conflict risks',
  'copilot.workbench.wholeBook.findConflicts.description': 'Catch naming drift and setting gaps early',
  'copilot.workbench.wholeBook.findConflicts.prompt': 'Check for naming conflicts, setting drift, and obvious gaps between frequent chapter mentions and the current world model.',

  'copilot.workbench.entity.eyebrow': 'Entity enrichment',
  'copilot.workbench.entity.title': ({ subject }) => `Complete types, attributes, constraints, and related clues around ${String(subject ?? '')}; do not assume it is only a character.`,
  'copilot.workbench.entity.composerLabel': 'Additional requirements',
  'copilot.workbench.entity.composerPlaceholder': ({ subject }) => `Add detail, such as "Prioritize ${String(subject ?? '')}'s links with the sect"`,
  'copilot.workbench.entity.complete.label': 'Complete current entity',
  'copilot.workbench.entity.complete.description': 'Fill in category, attributes, aliases, and key constraints',
  'copilot.workbench.entity.complete.prompt': ({ subject }) => `Please complete the key world data for ${String(subject ?? '')}. The entity may be a character, faction, location, organization, object, or concept. Identify the type first, then fill in aliases, attributes, constraints, and relationship clues.`,
  'copilot.workbench.entity.findRelations.label': 'Mine relationship clues',
  'copilot.workbench.entity.findRelations.description': 'Search for interaction evidence and latent links',
  'copilot.workbench.entity.findRelations.prompt': ({ subject }) => `Please identify the relationship clues and latent links most worth confirming around ${String(subject ?? '')}.`,
  'copilot.workbench.entity.collectEvidence.label': 'Collect chapter evidence',
  'copilot.workbench.entity.collectEvidence.description': 'Focus on the key passages supporting the enrichment',
  'copilot.workbench.entity.collectEvidence.prompt': ({ subject }) => `Please collect the chapter evidence that best supports enriching ${String(subject ?? '')}, ordered by importance.`,

  'copilot.workbench.relationships.eyebrow': 'Relationship research',
  'copilot.workbench.relationships.title': ({ subject }) => `Review missing relationships, interaction evidence, and label wording around ${String(subject ?? '')}.`,
  'copilot.workbench.relationships.composerLabel': 'Relationship research goal',
  'copilot.workbench.relationships.composerPlaceholder': ({ subject }) => `Add a goal such as "Find links between ${String(subject ?? '')} and factions that have evidence but are still missing"`,
  'copilot.workbench.relationships.find.label': 'Complete missing relationships',
  'copilot.workbench.relationships.find.description': 'Find the links around a focal entity that most deserve confirmation',
  'copilot.workbench.relationships.find.prompt': ({ subject }) => `Please review the relationship clues, missing links, and directions most worth confirming around ${String(subject ?? '')}.`,
  'copilot.workbench.relationships.labeling.label': 'Unify relationship labels',
  'copilot.workbench.relationships.labeling.description': 'Clean up vague, duplicate, or weak wording',
  'copilot.workbench.relationships.labeling.prompt': ({ subject }) => `Please unify the label wording for relationships around ${String(subject ?? '')} and point out those that are vague, duplicate, or semantically weak.`,
  'copilot.workbench.relationships.collect.label': 'Collect interaction evidence',
  'copilot.workbench.relationships.collect.description': 'Review key characters, factions, and chapter passages',
  'copilot.workbench.relationships.collect.prompt': ({ subject }) => `Please collect chapter evidence for ${String(subject ?? '')}'s interactions with key characters and factions, and mark the links that are most worth modeling.`,

  'copilot.workbench.draft.eyebrow': 'Draft cleanup',
  'copilot.workbench.draft.title': 'Organize current drafts, unify naming, fill missing fields, and mark candidates that can be confirmed directly.',
  'copilot.workbench.draft.composerLabel': 'Cleanup goal',
  'copilot.workbench.draft.composerPlaceholder': 'Add a goal such as "Unify draft naming and mark the entries worth confirming first"',
  'copilot.workbench.draft.review.label': 'Prioritize drafts',
  'copilot.workbench.draft.review.description': 'Find the entries most worth confirming or enriching first',
  'copilot.workbench.draft.review.prompt': 'Please organize the current drafts and identify the gaps most worth handling first.',
  'copilot.workbench.draft.normalize.label': 'Normalize draft naming',
  'copilot.workbench.draft.normalize.description': 'Converge duplicate concepts and alias drift',
  'copilot.workbench.draft.normalize.prompt': 'Please normalize naming, aliases, and duplicate concepts in the current drafts, prioritizing candidates that can be cleaned up directly.',
  'copilot.workbench.draft.fill.label': 'Fill missing fields',
  'copilot.workbench.draft.fill.description': 'Find drafts with sparse descriptions or missing fields',
  'copilot.workbench.draft.fill.prompt': 'Please identify entries in the current drafts that are missing fields, too brief, or obviously ready for enrichment, and rank them by value.',

  'copilot.errors.pollRunNotFound': 'This research run is no longer available. Please start a new one.',
  'copilot.errors.connectionInterrupted': 'Connection interrupted. Please try again shortly.',
  'copilot.errors.applyTargetStale': 'The target for this suggestion changed just now. Refresh and try again.',
  'copilot.errors.applyNotActionable': 'This suggestion cannot be applied right now.',
  'copilot.errors.applySuggestionNotFound': 'This suggestion is no longer available. Please generate it again.',
  'copilot.errors.applyFailed': 'Applying this suggestion did not succeed. Please try again later.',
  'copilot.errors.sessionRunActive': 'A research run is already active in this session. Wait for it to finish first.',
  'copilot.errors.tooManyActiveRuns': 'You already have too many active research runs. Please wait for the others to finish first.',
  'copilot.errors.tooManyGlobalRuns': 'The server is busy handling too many Copilot requests right now. Please try again later.',
  'copilot.errors.resumeRunNotFound': 'The interrupted run could not be found. Please start a new question instead.',
  'copilot.errors.resumeRunNotInterrupted': 'This run is not currently in a resumable state. Refresh and try again.',
  'copilot.errors.resumePromptMismatch': 'You cannot change the question when resuming an old run. Enter a new request below instead.',
  'copilot.errors.resumeRunNotResumable': 'This interrupted run does not have resumable progress. Please start a new one instead.',
  'copilot.errors.quotaExhausted': 'Your available quota is exhausted. Submit feedback to unlock more quota first.',
  'copilot.errors.requestBusy': 'The service is busy right now. Please try again shortly.',
  'copilot.errors.serviceUnavailable': 'The service is temporarily unavailable. Please try again later.',
  'copilot.errors.sessionConflict': 'The current session state does not allow a new research run right now. Please try again later.',
  'copilot.errors.runCreateFailed': 'Unable to start this research run right now. Please try again later.',
  'copilot.errors.connecting': 'Connecting...',

  // Model selector
  'copilot.model.default': 'Default model',
  'copilot.model.noProviders': 'Please configure a model provider in Settings first',
  'copilot.history.title': 'Session history',
  'copilot.history.empty': 'No session history',
  'copilot.history.emptyHint': 'Start a Copilot research session and it will appear here automatically.',
  'copilot.history.loadMore': 'Load more',
  'copilot.history.loading': 'Loading...',
  'copilot.history.runs': ({ count }) => `${String(count ?? 0)} runs`,
  'copilot.history.restore': 'Restore session',
  'copilot.history.filter.all': 'All',
  'copilot.history.filter.research': 'Research',
  'copilot.history.filter.currentEntity': 'Entity',
  'copilot.history.filter.draftCleanup': 'Draft',
  'copilot.history.mode.research': 'Research',
  'copilot.history.mode.current_entity': 'Entity',
  'copilot.history.mode.draft_cleanup': 'Draft',
  'copilot.history.scope.whole_book': 'Whole book',
  'copilot.history.scope.current_entity': 'Entity',
  'copilot.history.scope.current_tab': 'Tab',
} as const satisfies Record<string, UiMessageValue>

registerUiMessages({ zh: copilotZhMessages, en: copilotEnMessages })
